In [1]:
import json
import pandas as pd

file = open(r"D:\BOT_Prime\CIB_DELTA_back\output\data.json")
datas = json.load(file)
df = pd.DataFrame(columns=[
        'Name',
        'DOB', 
        'Gender', 
        'FatherName', 
        'CitizenshipDetails', 
        'PassportDetails', 
        'DrivingLicenseDetails',
        'VoterIDDetails',
        'PANDetails', 
        'CompanyDetails',
        'IndianEmbassyDetails',
        'BlackLists' 
    ])

num = 0
for data in datas["BulkOffLoading"]["Individuals"]["Item"]:
    # for key_value in data:
    # print("--------------------------- REal Data --------------------- \n")
    # print(data)
    dicts = {}
    data_keys = list(data.keys())
    # print(data_keys)
    for data_key in data_keys:
        # print(data_key)
        if isinstance(data[data_key], str):
            dicts[data_key] = data[data_key]
            print(dicts[data_key])
        
        else:
            # maintain Citizenship details and black list detail
            keys = list(data[data_key].keys())
            data_count = int(data[data_key][keys[0]])
            # print('DATA_COUNT',data_count)
            if data_count > 1: #here data with data_count greater than 1 will come in list format
                details = data[data_key][keys[1]]
                # if details contain 
                print('DETAILS',details)
                dicts[data_key] = ['|'.join(entry.values()) for entry in details] 
                print(dicts[data_key])
                
            elif data_count == 0:
                continue
            else:
                details = data[data_key][keys[1]]
                # print('next detail',details)
                dicts[data_key] = '|'.join(details.values())
            # df.loc[len(df)] = dicts
            
    # print(dicts)
    # print(f"--------------- Processed Data number {num} -----------------------" )
    print('Dictionary==========================================================>',dicts)
    num += 1
    if num == 2:
        break
    df.loc[len(df)] = dicts

BALRAM PRADHAN
2015-03-15
M
JITENDRA PRADHAN
DETAILS [{'Sector': 'Bank and Financial Institutions', 'BlacklistNumber': '5432', 'BlacklistedDate': '2071-01-21', 'BlacklistType': 'CF', 'NatureOfRelation': 'Guarantor'}, {'Sector': 'Bank and Financial Institutions', 'BlacklistNumber': '5432', 'BlacklistedDate': '2071-01-21', 'BlacklistType': 'CF', 'NatureOfRelation': 'Partner'}]
['Bank and Financial Institutions|5432|2071-01-21|CF|Guarantor', 'Bank and Financial Institutions|5432|2071-01-21|CF|Partner']
Dictionary==========================================================> {'Name': 'BALRAM PRADHAN', 'DOB': '2015-03-15', 'Gender': 'M', 'FatherName': 'JITENDRA PRADHAN', 'CitizenshipDetails': '2827|2046-01-11|Kathmandu', 'BlackLists': ['Bank and Financial Institutions|5432|2071-01-21|CF|Guarantor', 'Bank and Financial Institutions|5432|2071-01-21|CF|Partner']}
BHADRA BARAILI
2004-11-22
M
SAL BAHADUR BARAILI
Dictionary==========================================================> {'Name': 'BHADRA BARAILI', 'DOB': '2004-11-22', 'Gender': 'M', 'FatherName': 'SAL BAHADUR BARAILI', 'CitizenshipDetails': '2061/30387|2041-08-29|Sankhuwasabha', 'BlackLists': 'Bank and Financial Institutions|15073|2076-07-18|CF|Guarantor'}

In [113]:
df.count()

Name                     7
DOB                      7
Gender                   7
FatherName               7
CitizenshipDetails       7
PassportDetails          0
DrivingLicenseDetails    0
VoterIDDetails           0
PANDetails               2
CompanyDetails           0
IndianEmbassyDetails     0
BlackLists               7
dtype: int64

In [107]:
df.head(10)

,Name,DOB,Gender,FatherName,CitizenshipDetails,PassportDetails,DrivingLicenseDetails,VoterIDDetails,PANDetails,CompanyDetails,IndianEmbassyDetails,BlackLists
0,BALRAM PRADHAN,2015-03-15,M,JITENDRA PRADHAN,2827|2046-01-11|Kathmandu,NaN,NaN,NaN,NaN,NaN,NaN,[Bank and Financial Institutions|5432|2071-01-...
1,BHADRA BARAILI,2004-11-22,M,SAL BAHADUR BARAILI,2061/30387|2041-08-29|Sankhuwasabha,NaN,NaN,NaN,NaN,NaN,NaN,Bank and Financial Institutions|15073|2076-07-...
2,SUDHA DEVI DARUKA,2030-01-01,F,SAWAR MAL RANGUTA,10523|2068-08-04|Parsa,NaN,NaN,NaN,NaN,NaN,NaN,Bank and Financial Institutions|14770|2076-06-...
3,RAJESH RAJ VERMA,2030-08-22,M,KRISHNA RAJ VERMA,5237|2047-07-20|Saptari,NaN,NaN,NaN,NaN,NaN,NaN,[Bank and Financial Institutions|13189|2076-03...
4,NEELAM RIJAL,2029-05-21,F,TARAK PRASAD RIJAL,22961|2052-08-13|Morang,NaN,NaN,NaN,NaN,NaN,NaN,[Bank and Financial Institutions|11812|2075-09...
5,JIVAN GIRI,2036-01-29,M,RAM CHANDRA GIRI,2727/5942|2052-04-22|Morang,NaN,NaN,NaN,304598155|2067-12-09|Jhapa,NaN,NaN,Bank and Financial Institutions|69325|2080-02-...
6,KUMAR ROKKA CHHETRI,2031-02-29,M,BASANTA ROKKA CHHETRI,"[24557|2049-12-25|Makawanpur, 24557|2049-12-25...",NaN,NaN,NaN,24557|2049-12-25|Rasuwa,NaN,NaN,Bank and Financial Institutions|68051|2080-02-...

In [115]:
import numpy as np
def drop_dupicates(df):
    both_present = df[(~df['CitizenshipDetails'].isnull()) & (~df['PANDetails'].isnull())]
    # both_present
    duplicated_rows = both_present.copy()
    # duplicated_rows
    both_present_indices = both_present.index 

    df.drop(index=both_present_indices, inplace=True)
    for index, row in both_present.iterrows():
        both_present.at[index, 'CitizenshipDetails'] = np.nan

    for index, row in duplicated_rows.iterrows():
        duplicated_rows.at[index, 'PANDetails'] = np.nan

    df = pd.concat([df, both_present, duplicated_rows], ignore_index=True)
    return df
data_df = drop_dupicates(df)

In [117]:
df.count()

Name                     24
DOB                      24
Gender                   24
FatherName               24
CitizenshipDetails       24
PassportDetails           0
DrivingLicenseDetails     0
VoterIDDetails            1
PANDetails                0
CompanyDetails            0
IndianEmbassyDetails      0
BlackLists               24
dtype: int64

In [92]:
data =    {
                    "Name": "JIVAN GIRI",
                    "DOB": "2036-01-29",
                    "Gender": "M",
                    "FatherName": "RAM CHANDRA GIRI",
                    "CitizenshipDetails": {
                        "CitizenshipCount": "1",
                        "Citizenship": {
                            "CitizenshipNumber": "2727/5942",
                            "CitizenshipIssuedDate": "2052-04-22",
                            "CitizenshipIssuedDistrict": "Morang"
                        }
                    },
                    "PassportDetails": {
                        "PassportCount": "0"
                    },
                    "DrivingLicenseDetails": {
                        "DrivingLicenseCount": "0"
                    },
                    "VoterIDDetails": {
                        "VoterIdCount": "0"
                    },
                    "PANDetails": {
                        "PANCount": "1",
                        "PAN": {
                            "PAN": "304598155",
                            "PANIssuedDate": "2067-12-09",
                            "PANIssuedDistrict": "Jhapa"
                        }
                    },
                    "IndianEmbassyDetails": {
                        "IndianEmbassyCount": "0"
                    },
                    "BlackLists": {
                        "BlackListCount": "1",
                        "BlackList": {
                            "Sector": "Bank and Financial Institutions",
                            "BlacklistNumber": "69325",
                            "BlacklistedDate": "2080-02-29",
                            "BlacklistType": "CF",
                            "NatureOfRelation": "Guarantor"
                        }
                    }
                }

In [98]:
dicts = {}
df = pd.DataFrame(columns=[
        'Name',
        'DOB', 
        'Gender', 
        'FatherName', 
        'CitizenshipDetails', 
        'PassportDetails', 
        'DrivingLicenseDetails',
        'VoterIDDetails',
        'PANDetails', 
        'CompanyDetails',
        'IndianEmbassyDetails',
        'BlackLists' 
    ])
        
dicts = {}
data_keys = list(data.keys())
# print(data_keys)
for data_key in data_keys:
    # print(data_key)
    if isinstance(data[data_key], str):
        dicts[data_key] = data[data_key]
        print(dicts[data_key])
    
    else:
        # maintain Citizenship details and black list detail
        keys = list(data[data_key].keys())
        data_count = int(data[data_key][keys[0]])
        # print('DATA_COUNT',data_count)
        if data_count > 1: #here data with data_count greater than 1 will come in list format
            details = data[data_key][keys[1]]
            # if details contain 
            print('DETAILS',details)
            dicts[data_key] = ['|'.join(entry.values()) for entry in details] 
            print(dicts[data_key])
            df.loc[len(df)] = dicts
            
        elif data_count == 0:
            dicts[data_key] =''
            continue
        else:
            details = data[data_key][keys[1]]
            # if 'CitizenshipNumber' in details:
        
            # print('next detail',details)
            dicts[data_key] = '|'.join(details.values())
            print('else==>',dicts[data_key])
            df.loc[len(df)] = dicts

# df.loc[len(df)] = dicts

JIVAN GIRI
2036-01-29
M
RAM CHANDRA GIRI
else==> 2727/5942|2052-04-22|Morang
else==> 304598155|2067-12-09|Jhapa
else==> Bank and Financial Institutions|69325|2080-02-29|CF|Guarantor

In [99]:
df

,Name,DOB,Gender,FatherName,CitizenshipDetails,PassportDetails,DrivingLicenseDetails,VoterIDDetails,PANDetails,CompanyDetails,IndianEmbassyDetails,BlackLists
0,JIVAN GIRI,2036-01-29,M,RAM CHANDRA GIRI,2727/5942|2052-04-22|Morang,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,JIVAN GIRI,2036-01-29,M,RAM CHANDRA GIRI,2727/5942|2052-04-22|Morang,,,,304598155|2067-12-09|Jhapa,NaN,NaN,NaN
2,JIVAN GIRI,2036-01-29,M,RAM CHANDRA GIRI,2727/5942|2052-04-22|Morang,,,,304598155|2067-12-09|Jhapa,NaN,,Bank and Financial Institutions|69325|2080-02-...

In [20]:
df.head(20)

,Name,DOB,Gender,FatherName,CitizenshipDetails,PassportDetails,DrivingLicenseDetails,VoterIDDetails,PANDetails,CompanyDetails,IndianEmbassyDetails,BlackLists,Account_Nature,Status
0,AALI SUB REMIT SEWA PVT. LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,606804729|2075-12-12|Kathmandu,211424/075/076|NULL|Office Of Company Registrar,NaN,Bank and Financial Institutions|32165|2078-11-...,Institutions,new
1,RECHAL ELECTRIC CENTRE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602297651|2071-04-22|Banke,23554-071/072|NULL|Department of commerce and ...,NaN,Bank and Financial Institutions|32166|2078-11-...,Institutions,new
2,TIRUPATI FOOT WEAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602164991|2071-02-22|Sunasari,13105/074/075|NULL|Office of Cottage and Small...,NaN,Bank and Financial Institutions|32809|2078-11-...,Institutions,new
3,SUPA DEURALI ALMUNIUM AND STEEL UDHYOG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,611769888|2076-05-18|Rupandehi,19006/076/77|NULL|Office of Cottage and Small ...,NaN,Bank and Financial Institutions|33066|2078-11-...,Institutions,new
4,MAHALAXMI DEVI REFRIGERATION WORKSHOP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,615455828|2077-11-26|Bhaktapur,63|NULL|District Development Committee,NaN,Bank and Financial Institutions|32147|2078-11-...,Institutions,new
5,SHIVSHAKTI HARDWARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305171805|2068-07-28|Dhanusha,2925/405/068/69|NULL|Office of Cottage and Sma...,NaN,Bank and Financial Institutions|32220|2078-11-...,Institutions,new
6,AJIMA ORGANIC KRISHI AND PASHUPALAN FARM PVT LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602439134|2071-08-12|Kathmandu,128818/071/072|NULL|Office Of Company Registrar,NaN,Bank and Financial Institutions|32230|2078-11-...,Institutions,new
7,RAGINI SUPPLIERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602998356|2071-10-27|Rupandehi,34768/071|NULL|Department of Commerce,NaN,Bank and Financial Institutions|32272|2078-11-...,Institutions,new
8,BAJRA GURU ENTERPRISES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,605748396|2073-11-05|Kathmandu,133218/073/74|NULL|Department of Commerce,NaN,Bank and Financial Institutions|32273|2078-11-...,Institutions,new
9,RARAHANG NIRMAN SEWA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,612510304|2076-08-09|Ilam,1970/067/68|NULL|Office of Cottage and Small I...,NaN,Bank and Financial Institutions|32276|2078-11-...,Institutions,new
10,VANADIUM TRADE LINK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,611961028|2076-05-30|Kathmandu,154918/077/78|NULL|Department of commerce and ...,NaN,Bank and Financial Institutions|32292|2078-11-...,Institutions,new
11,KAVRE REAL ESTATES AND BUILDERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,604334817|2073-08-13|Kavre,156826/073/074|NULL|Office Of Company Registrar,NaN,Bank and Financial Institutions|65814|2080-02-...,Institutions,new
12,SUBA CONSTRUCTION PVT LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609920574|2077-10-19|Kathmandu,254314/077/078|NULL|Department of commerce and...,NaN,Bank and Financial Institutions|32304|2078-11-...,Institutions,new
13,N.D.C COLD STORES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[305198310|2068-06-09|Banke, 305198310|2068-09...","[20206/068/068|NULL|Department of Commerce, 20...",NaN,Bank and Financial Institutions|32953|2078-11-...,Institutions,new
14,JAY SHREE RUDRA BINAYAK ENTERPRISES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600306436|2068-06-02|Kathmandu,684|NULL|Municipality Office,NaN,Bank and Financial Institutions|32321|2078-11-...,Institutions,new
15,NEW JAMACHOWK SUPPLIERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603286661|2072-04-07|Kathmandu,122495/072/73|NULL|Department of commerce and ...,NaN,Bank and Financial Institutions|32324|2078-11-...,Institutions,new
16,ALL IN ONE TECHNICAL TRAINING INSTITUTE A.I.O.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[602611921|2071-07-19|Bhaktapur, 602611921|207...",1089/071/072|NULL|Office of Cottage and Small ...,NaN,Bank and Financial Institutions|32801|2078-11-...,Institutions,new
17,MIG NEPAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,606615002|2075-05-14|Kaski,197094/075/076|NULL|Office Of Company Registrar,NaN,Bank and Financial Institutions|67824|2080-02-...,Institutions,new
18,GRIHA LAXMI TRADERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,605628863|2073-09-29|Mahotari,3658/63/073/74|NULL|Office of Cottage and Smal...,NaN,[Bank and Financial Institutions|46255|2079-06...,Institutions,new

In [5]:
import json
import pandas as pd

file = open(r"D:\BOT_Prime\CIB_DELTA_back\output\data.json")
datas = json.load(file)
df = pd.DataFrame(columns=[
        'Name',
        'DOB', 
        'Gender', 
        'FatherName', 
        'CitizenshipDetails', 
        'PassportDetails', 
        'DrivingLicenseDetails',
        'VoterIDDetails',
        'PANDetails', 
        'CompanyDetails',
        'IndianEmbassyDetails',
        'BlackLists' 
    ])

num = 0
for data in datas["BulkOffLoading"]["Institutions"]["Item"]:
    # print(data)
    # data = 
    data_list = []
    dicts = {}
    data_keys = list(data.keys())
    # print(data_keys)
    for data_key in data_keys[:1]:
        dicts[data_key] = data[data_key]
        # print(dicts)
    for data_key in sorted(data_keys[1:]):
        # print(data_key)
        # print(data[data_key])
        keys = list(data[data_key].keys())
        # print('key------------',keys)
        data_count = int(data[data_key][keys[0]])
        if data_count > 1:
            details = data[data_key][keys[1]]
            # print('detail',details)
            if "BlackList" in data_key:
                dicts[data_key] = ['|'.join(detail.values()) for detail in details]
                # print(dicts)
                continue
            else:  
                for detail in details:
                    dicts[data_key] = '|'.join(detail.values())
                    # print('detttttttttttttttt',dicts[data_key])
                    # print('COUNT GREATER THAN 1',dicts)
                    df.loc[len(df)] = dicts
        elif data_count == 0:
            continue
        else:
            details = data[data_key][keys[1]]
            # print('DETAIL',details)
            dicts[data_key] = '|'.join(details.values())
            # df.loc[len(df)] = dicts
            # print(dicts)
        # if "BlackList" not in data_key:
            # df.loc[len(df)] = dicts
        #     print('================',dicts[data_key])
        #     print('================',dicts)
            # del dicts[data_key]
            # print('TTTTTTTTTTt================',dicts)
    df.loc[len(df)] = dicts
    num += 1
    if num == 60:
        break
    # df.to_excel('black_institutional.xlsx',index=False)

In [6]:
df.head(30)

,Name,DOB,Gender,FatherName,CitizenshipDetails,PassportDetails,DrivingLicenseDetails,VoterIDDetails,PANDetails,CompanyDetails,IndianEmbassyDetails,BlackLists
0,AALI SUB REMIT SEWA PVT. LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,606804729|2075-12-12|Kathmandu,211424/075/076|NULL|Office Of Company Registrar,NaN,Bank and Financial Institutions|32165|2078-11-...
1,RECHAL ELECTRIC CENTRE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602297651|2071-04-22|Banke,23554-071/072|NULL|Department of commerce and ...,NaN,Bank and Financial Institutions|32166|2078-11-...
2,TIRUPATI FOOT WEAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602164991|2071-02-22|Sunasari,13105/074/075|NULL|Office of Cottage and Small...,NaN,Bank and Financial Institutions|32809|2078-11-...
3,SUPA DEURALI ALMUNIUM AND STEEL UDHYOG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,611769888|2076-05-18|Rupandehi,19006/076/77|NULL|Office of Cottage and Small ...,NaN,Bank and Financial Institutions|33066|2078-11-...
4,MAHALAXMI DEVI REFRIGERATION WORKSHOP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,615455828|2077-11-26|Bhaktapur,63|NULL|District Development Committee,NaN,Bank and Financial Institutions|32147|2078-11-...
5,SHIVSHAKTI HARDWARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305171805|2068-07-28|Dhanusha,2925/405/068/69|NULL|Office of Cottage and Sma...,NaN,Bank and Financial Institutions|32220|2078-11-...
6,AJIMA ORGANIC KRISHI AND PASHUPALAN FARM PVT LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602439134|2071-08-12|Kathmandu,128818/071/072|NULL|Office Of Company Registrar,NaN,Bank and Financial Institutions|32230|2078-11-...
7,RAGINI SUPPLIERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602998356|2071-10-27|Rupandehi,34768/071|NULL|Department of Commerce,NaN,Bank and Financial Institutions|32272|2078-11-...
8,BAJRA GURU ENTERPRISES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,605748396|2073-11-05|Kathmandu,133218/073/74|NULL|Department of Commerce,NaN,Bank and Financial Institutions|32273|2078-11-...
9,RARAHANG NIRMAN SEWA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,612510304|2076-08-09|Ilam,1970/067/68|NULL|Office of Cottage and Small I...,NaN,Bank and Financial Institutions|32276|2078-11-...
10,VANADIUM TRADE LINK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,611961028|2076-05-30|Kathmandu,154918/077/78|NULL|Department of commerce and ...,NaN,Bank and Financial Institutions|32292|2078-11-...
11,KAVRE REAL ESTATES AND BUILDERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,604334817|2073-08-13|Kavre,156826/073/074|NULL|Office Of Company Registrar,NaN,Bank and Financial Institutions|65814|2080-02-...
12,SUBA CONSTRUCTION PVT LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609920574|2077-10-19|Kathmandu,254314/077/078|NULL|Department of commerce and...,NaN,Bank and Financial Institutions|32304|2078-11-...
13,N.D.C COLD STORES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20206/068/068|NULL|Department of Commerce,NaN,Bank and Financial Institutions|32953|2078-11-...
14,N.D.C COLD STORES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20206/068/069|NULL|Department of Commerce,NaN,Bank and Financial Institutions|32953|2078-11-...
15,N.D.C COLD STORES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305198310|2068-06-09|Banke,20206/068/069|NULL|Department of Commerce,NaN,Bank and Financial Institutions|32953|2078-11-...
16,N.D.C COLD STORES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305198310|2068-09-02|Banke,20206/068/069|NULL|Department of Commerce,NaN,Bank and Financial Institutions|32953|2078-11-...
17,N.D.C COLD STORES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305198310|2068-09-02|Banke,20206/068/069|NULL|Department of Commerce,NaN,Bank and Financial Institutions|32953|2078-11-...
18,JAY SHREE RUDRA BINAYAK ENTERPRISES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600306436|2068-06-02|Kathmandu,684|NULL|Municipality Office,NaN,Bank and Financial Institutions|32321|2078-11-...
19,NEW JAMACHOWK SUPPLIERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603286661|2072-04-07|Kathmandu,122495/072/73|NULL|Department of commerce and ...,NaN,Bank and Financial Institutions|32324|2078-11-...
20,ALL IN ONE TECHNICAL TRAINING INSTITUTE A.I.O.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602611921|2071-07-19|Bhaktapur,1089/071/072|NULL|Office of Cottage and Small ...,NaN,Bank and Financial Institutions|32801|2078-11-...
21,ALL IN ONE TECHNICAL TRAINING INSTITUTE A.I.O.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602611921|2071-07-19|Dolakha,1089/071/072|NULL|Office of Cottage and Small ...,NaN,Bank and Financial Institutions|32801|2078-11-...
22,ALL IN ONE TECHNICAL TRAINING INSTITUTE A.I.O.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602611921|2071-07-19|Dolakha,1089/071/072|NULL|Office of Cottage and Small ...,NaN,Bank and Financial Institutions|32801|2078-11-...
23,MIG NEPAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,606615002|2075-05-14|Kaski,197094/075/076|NULL|Office Of Company Registrar,NaN,Bank and Financial Institutions|67824|2080-02-...
24,GRIHA LAXMI TRADERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,605628863|2073-09-29|Mahotari,3658/63/073/74|NULL|Office of Cottage and Smal...,NaN,[Bank and Financial Institutions|46255|2079-06...
25,SHIVAM ENTERPRISES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603871227|2072-10-24|Chitawan,16/073/074|NULL|Office of Cottage and Small In...,NaN,Bank and Financial Institutions|32331|2078-11-...
26,WEE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,616481246|2078-05-09|Rupandehi,7879040025|NULL|Municipality Office,NaN,[Bank and Financial Institutions|33299|2078-12...
27,MUSKAN NIRMAN SEWA AND SUPPLIERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,602559979|2071-06-03|Doti,48/065/066|NULL|District Development Committee,NaN,Bank and Financial Institutions|32354|2078-11-...
28,ALAS FOOD PRODUCT AND SUPPLIERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,601128554|2070-03-03|Lalitpur,3809|NULL|VDC Office,NaN,Bank and Financial Institutions|32366|2078-11-...
29,AAROSI MULTIPROPOSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609756858|2077-04-05|Chitawan,237918/76/077|NULL|Office Of Company Registrar,NaN,Bank and Financial Institutions|32369|2078-11-...

In [2]:
import json
import pandas as pd

file = open(r"D:\BOT_Prime\CIB_DELTA_back\output\data.json")
datas = json.load(file)
df = pd.DataFrame(columns=[
        'Name',
        'DOB', 
        'Gender', 
        'FatherName', 
        'CitizenshipDetails', 
        'PassportDetails', 
        'DrivingLicenseDetails',
        'VoterIDDetails',
        'PANDetails', 
        'CompanyDetails',
        'IndianEmbassyDetails',
        'BlackLists' 
    ])

num = 0
for data in datas["BulkOffLoading"]["Institutions"]["Item"]: 
    dicts = {}
    data_keys = list(data.keys())
    # print(data_keys)
    for data_key in data_keys[:1]:
        dicts[data_key] = data[data_key]
        # print(dicts)
    for data_key in sorted(data_keys[1:]):
        # print(data_key)
        # print(data[data_key])
        keys = list(data[data_key].keys())
        # print('key------------',keys)
        data_count = int(data[data_key][keys[0]])
        print(data_count)
        if 'PANDetails' in data_key:
            details = data[data_key][keys[1]]
            dicts[data_key] = '|'.join(details.values())
            print('pan========================',dicts)
        if data_count == 1:
            details = data[data_key][keys[1]]
            dicts[data_key] = '|'.join(details.values())
            print('DATACOUNT IS EQUAL TO ONE',dicts)
        elif data_count > 1:
            details = data[data_key][keys[1]]
            # print('detail',details)
            if "BlackList" in data_key:
                dicts[data_key] = ['|'.join(detail.values()) for detail in details]
                # print(dicts)
                continue
                
            else:  
                for detail in details:
                    dicts[data_key] = '|'.join(detail.values())
                    # print('detttttttttttttttt',dicts[data_key])
                    print('COUNT GREATER THAN 1',dicts)
                    df.loc[len(df)] = dicts
        elif data_count == 0:
            continue

1
DATACOUNT IS EQUAL TO ONE {'Name': 'AALI SUB REMIT SEWA PVT. LTD.', 'BlackLists': 'Bank and Financial Institutions|32165|2078-11-08|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'AALI SUB REMIT SEWA PVT. LTD.', 'BlackLists': 'Bank and Financial Institutions|32165|2078-11-08|NON CF|Borrower', 'CompanyDetails': '211424/075/076|NULL|Office Of Company Registrar'}
1
pan======================== {'Name': 'AALI SUB REMIT SEWA PVT. LTD.', 'BlackLists': 'Bank and Financial Institutions|32165|2078-11-08|NON CF|Borrower', 'CompanyDetails': '211424/075/076|NULL|Office Of Company Registrar', 'PANDetails': '606804729|2075-12-12|Kathmandu'}
DATACOUNT IS EQUAL TO ONE {'Name': 'AALI SUB REMIT SEWA PVT. LTD.', 'BlackLists': 'Bank and Financial Institutions|32165|2078-11-08|NON CF|Borrower', 'CompanyDetails': '211424/075/076|NULL|Office Of Company Registrar', 'PANDetails': '606804729|2075-12-12|Kathmandu'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'RECHAL ELECTRIC CENTRE', 'BlackLists': 'Bank and Financial Institutions|32166|2078-11-08|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'RECHAL ELECTRIC CENTRE', 'BlackLists': 'Bank and Financial Institutions|32166|2078-11-08|NON CF|Borrower', 'CompanyDetails': '23554-071/072|NULL|Department of commerce and Supply Management'}
1
pan======================== {'Name': 'RECHAL ELECTRIC CENTRE', 'BlackLists': 'Bank and Financial Institutions|32166|2078-11-08|NON CF|Borrower', 'CompanyDetails': '23554-071/072|NULL|Department of commerce and Supply Management', 'PANDetails': '602297651|2071-04-22|Banke'}
DATACOUNT IS EQUAL TO ONE {'Name': 'RECHAL ELECTRIC CENTRE', 'BlackLists': 'Bank and Financial Institutions|32166|2078-11-08|NON CF|Borrower', 'CompanyDetails': '23554-071/072|NULL|Department of commerce and Supply Management', 'PANDetails': '602297651|2071-04-22|Banke'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'TIRUPATI FOOT WEAR', 'BlackLists': 'Bank and Financial Institutions|32809|2078-11-23|CF|Guarantor'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'TIRUPATI FOOT WEAR', 'BlackLists': 'Bank and Financial Institutions|32809|2078-11-23|CF|Guarantor', 'CompanyDetails': '13105/074/075|NULL|Office of Cottage and Small Industry'}
1
pan======================== {'Name': 'TIRUPATI FOOT WEAR', 'BlackLists': 'Bank and Financial Institutions|32809|2078-11-23|CF|Guarantor', 'CompanyDetails': '13105/074/075|NULL|Office of Cottage and Small Industry', 'PANDetails': '602164991|2071-02-22|Sunasari'}
DATACOUNT IS EQUAL TO ONE {'Name': 'TIRUPATI FOOT WEAR', 'BlackLists': 'Bank and Financial Institutions|32809|2078-11-23|CF|Guarantor', 'CompanyDetails': '13105/074/075|NULL|Office of Cottage and Small Industry', 'PANDetails': '602164991|2071-02-22|Sunasari'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'SUPA DEURALI ALMUNIUM AND STEEL UDHYOG', 'BlackLists': 'Bank and Financial Institutions|33066|2078-11-29|CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'SUPA DEURALI ALMUNIUM AND STEEL UDHYOG', 'BlackLists': 'Bank and Financial Institutions|33066|2078-11-29|CF|Borrower', 'CompanyDetails': '19006/076/77|NULL|Office of Cottage and Small Industry'}
1
pan======================== {'Name': 'SUPA DEURALI ALMUNIUM AND STEEL UDHYOG', 'BlackLists': 'Bank and Financial Institutions|33066|2078-11-29|CF|Borrower', 'CompanyDetails': '19006/076/77|NULL|Office of Cottage and Small Industry', 'PANDetails': '611769888|2076-05-18|Rupandehi'}
DATACOUNT IS EQUAL TO ONE {'Name': 'SUPA DEURALI ALMUNIUM AND STEEL UDHYOG', 'BlackLists': 'Bank and Financial Institutions|33066|2078-11-29|CF|Borrower', 'CompanyDetails': '19006/076/77|NULL|Office of Cottage and Small Industry', 'PANDetails': '611769888|2076-05-18|Rupandehi'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'MAHALAXMI DEVI REFRIGERATION WORKSHOP', 'BlackLists': 'Bank and Financial Institutions|32147|2078-11-08|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'MAHALAXMI DEVI REFRIGERATION WORKSHOP', 'BlackLists': 'Bank and Financial Institutions|32147|2078-11-08|NON CF|Borrower', 'CompanyDetails': '63|NULL|District Development Committee'}
1
pan======================== {'Name': 'MAHALAXMI DEVI REFRIGERATION WORKSHOP', 'BlackLists': 'Bank and Financial Institutions|32147|2078-11-08|NON CF|Borrower', 'CompanyDetails': '63|NULL|District Development Committee', 'PANDetails': '615455828|2077-11-26|Bhaktapur'}
DATACOUNT IS EQUAL TO ONE {'Name': 'MAHALAXMI DEVI REFRIGERATION WORKSHOP', 'BlackLists': 'Bank and Financial Institutions|32147|2078-11-08|NON CF|Borrower', 'CompanyDetails': '63|NULL|District Development Committee', 'PANDetails': '615455828|2077-11-26|Bhaktapur'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'SHIVSHAKTI HARDWARE', 'BlackLists': 'Bank and Financial Institutions|32220|2078-11-09|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'SHIVSHAKTI HARDWARE', 'BlackLists': 'Bank and Financial Institutions|32220|2078-11-09|NON CF|Borrower', 'CompanyDetails': '2925/405/068/69|NULL|Office of Cottage and Small Industry'}
1
pan======================== {'Name': 'SHIVSHAKTI HARDWARE', 'BlackLists': 'Bank and Financial Institutions|32220|2078-11-09|NON CF|Borrower', 'CompanyDetails': '2925/405/068/69|NULL|Office of Cottage and Small Industry', 'PANDetails': '305171805|2068-07-28|Dhanusha'}
DATACOUNT IS EQUAL TO ONE {'Name': 'SHIVSHAKTI HARDWARE', 'BlackLists': 'Bank and Financial Institutions|32220|2078-11-09|NON CF|Borrower', 'CompanyDetails': '2925/405/068/69|NULL|Office of Cottage and Small Industry', 'PANDetails': '305171805|2068-07-28|Dhanusha'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'AJIMA ORGANIC KRISHI AND PASHUPALAN FARM PVT LTD', 'BlackLists': 'Bank and Financial Institutions|32230|2078-11-09|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'AJIMA ORGANIC KRISHI AND PASHUPALAN FARM PVT LTD', 'BlackLists': 'Bank and Financial Institutions|32230|2078-11-09|NON CF|Borrower', 'CompanyDetails': '128818/071/072|NULL|Office Of Company Registrar'}
1
pan======================== {'Name': 'AJIMA ORGANIC KRISHI AND PASHUPALAN FARM PVT LTD', 'BlackLists': 'Bank and Financial Institutions|32230|2078-11-09|NON CF|Borrower', 'CompanyDetails': '128818/071/072|NULL|Office Of Company Registrar', 'PANDetails': '602439134|2071-08-12|Kathmandu'}
DATACOUNT IS EQUAL TO ONE {'Name': 'AJIMA ORGANIC KRISHI AND PASHUPALAN FARM PVT LTD', 'BlackLists': 'Bank and Financial Institutions|32230|2078-11-09|NON CF|Borrower', 'CompanyDetails': '128818/071/072|NULL|Office Of Company Registrar', 'PANDetails': '602439134|2071-08-12|Kathmandu'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'RAGINI SUPPLIERS', 'BlackLists': 'Bank and Financial Institutions|32272|2078-11-10|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'RAGINI SUPPLIERS', 'BlackLists': 'Bank and Financial Institutions|32272|2078-11-10|NON CF|Borrower', 'CompanyDetails': '34768/071|NULL|Department of Commerce'}
1
pan======================== {'Name': 'RAGINI SUPPLIERS', 'BlackLists': 'Bank and Financial Institutions|32272|2078-11-10|NON CF|Borrower', 'CompanyDetails': '34768/071|NULL|Department of Commerce', 'PANDetails': '602998356|2071-10-27|Rupandehi'}
DATACOUNT IS EQUAL TO ONE {'Name': 'RAGINI SUPPLIERS', 'BlackLists': 'Bank and Financial Institutions|32272|2078-11-10|NON CF|Borrower', 'CompanyDetails': '34768/071|NULL|Department of Commerce', 'PANDetails': '602998356|2071-10-27|Rupandehi'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'BAJRA GURU ENTERPRISES', 'BlackLists': 'Bank and Financial Institutions|32273|2078-11-10|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'BAJRA GURU ENTERPRISES', 'BlackLists': 'Bank and Financial Institutions|32273|2078-11-10|NON CF|Borrower', 'CompanyDetails': '133218/073/74|NULL|Department of Commerce'}
1
pan======================== {'Name': 'BAJRA GURU ENTERPRISES', 'BlackLists': 'Bank and Financial Institutions|32273|2078-11-10|NON CF|Borrower', 'CompanyDetails': '133218/073/74|NULL|Department of Commerce', 'PANDetails': '605748396|2073-11-05|Kathmandu'}
DATACOUNT IS EQUAL TO ONE {'Name': 'BAJRA GURU ENTERPRISES', 'BlackLists': 'Bank and Financial Institutions|32273|2078-11-10|NON CF|Borrower', 'CompanyDetails': '133218/073/74|NULL|Department of Commerce', 'PANDetails': '605748396|2073-11-05|Kathmandu'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'RARAHANG NIRMAN SEWA', 'BlackLists': 'Bank and Financial Institutions|32276|2078-11-10|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'RARAHANG NIRMAN SEWA', 'BlackLists': 'Bank and Financial Institutions|32276|2078-11-10|NON CF|Borrower', 'CompanyDetails': '1970/067/68|NULL|Office of Cottage and Small Industry'}
1
pan======================== {'Name': 'RARAHANG NIRMAN SEWA', 'BlackLists': 'Bank and Financial Institutions|32276|2078-11-10|NON CF|Borrower', 'CompanyDetails': '1970/067/68|NULL|Office of Cottage and Small Industry', 'PANDetails': '612510304|2076-08-09|Ilam'}
DATACOUNT IS EQUAL TO ONE {'Name': 'RARAHANG NIRMAN SEWA', 'BlackLists': 'Bank and Financial Institutions|32276|2078-11-10|NON CF|Borrower', 'CompanyDetails': '1970/067/68|NULL|Office of Cottage and Small Industry', 'PANDetails': '612510304|2076-08-09|Ilam'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'VANADIUM TRADE LINK', 'BlackLists': 'Bank and Financial Institutions|32292|2078-11-10|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'VANADIUM TRADE LINK', 'BlackLists': 'Bank and Financial Institutions|32292|2078-11-10|NON CF|Borrower', 'CompanyDetails': '154918/077/78|NULL|Department of commerce and Supply Management'}
1
pan======================== {'Name': 'VANADIUM TRADE LINK', 'BlackLists': 'Bank and Financial Institutions|32292|2078-11-10|NON CF|Borrower', 'CompanyDetails': '154918/077/78|NULL|Department of commerce and Supply Management', 'PANDetails': '611961028|2076-05-30|Kathmandu'}
DATACOUNT IS EQUAL TO ONE {'Name': 'VANADIUM TRADE LINK', 'BlackLists': 'Bank and Financial Institutions|32292|2078-11-10|NON CF|Borrower', 'CompanyDetails': '154918/077/78|NULL|Department of commerce and Supply Management', 'PANDetails': '611961028|2076-05-30|Kathmandu'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'KAVRE REAL ESTATES AND BUILDERS', 'BlackLists': 'Bank and Financial Institutions|65814|2080-02-01|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'KAVRE REAL ESTATES AND BUILDERS', 'BlackLists': 'Bank and Financial Institutions|65814|2080-02-01|NON CF|Borrower', 'CompanyDetails': '156826/073/074|NULL|Office Of Company Registrar'}
1
pan======================== {'Name': 'KAVRE REAL ESTATES AND BUILDERS', 'BlackLists': 'Bank and Financial Institutions|65814|2080-02-01|NON CF|Borrower', 'CompanyDetails': '156826/073/074|NULL|Office Of Company Registrar', 'PANDetails': '604334817|2073-08-13|Kavre'}
DATACOUNT IS EQUAL TO ONE {'Name': 'KAVRE REAL ESTATES AND BUILDERS', 'BlackLists': 'Bank and Financial Institutions|65814|2080-02-01|NON CF|Borrower', 'CompanyDetails': '156826/073/074|NULL|Office Of Company Registrar', 'PANDetails': '604334817|2073-08-13|Kavre'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'SUBA CONSTRUCTION PVT LTD', 'BlackLists': 'Bank and Financial Institutions|32304|2078-11-10|NON CF|Borrower'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'SUBA CONSTRUCTION PVT LTD', 'BlackLists': 'Bank and Financial Institutions|32304|2078-11-10|NON CF|Borrower', 'CompanyDetails': '254314/077/078|NULL|Department of commerce and Supply Management'}
1
pan======================== {'Name': 'SUBA CONSTRUCTION PVT LTD', 'BlackLists': 'Bank and Financial Institutions|32304|2078-11-10|NON CF|Borrower', 'CompanyDetails': '254314/077/078|NULL|Department of commerce and Supply Management', 'PANDetails': '609920574|2077-10-19|Kathmandu'}
DATACOUNT IS EQUAL TO ONE {'Name': 'SUBA CONSTRUCTION PVT LTD', 'BlackLists': 'Bank and Financial Institutions|32304|2078-11-10|NON CF|Borrower', 'CompanyDetails': '254314/077/078|NULL|Department of commerce and Supply Management', 'PANDetails': '609920574|2077-10-19|Kathmandu'}
1
DATACOUNT IS EQUAL TO ONE {'Name': 'N.D.C COLD STORES', 'BlackLists': 'Bank and Financial Institutions|32953|2078-11-27|CF|Borrower'}
2
COUNT GREATER THAN 1 {'Name': 'N.D.C COLD STORES', 'BlackLists': 'Bank and Financial Institutions|32953|2078-11-27|CF|Borrower', 'CompanyDetails': '20206/068/068|NULL|Department of Commerce'}
COUNT GREATER THAN 1 {'Name': 'N.D.C COLD STORES', 'BlackLists': 'Bank and Financial Institutions|32953|2078-11-27|CF|Borrower', 'CompanyDetails': '20206/068/069|NULL|Department of Commerce'}
2

AttributeError: 'list' object has no attribute 'values'

In [1]:
# df.head(50)

In [107]:
import pandas as pd

df = pd.DataFrame(columns=[
        'Name',
        'DOB', 
        'Gender', 
        'FatherName', 
        'CitizenshipDetails', 
        'PassportDetails', 
        'DrivingLicenseDetails',
        'VoterIDDetails',
        'PANDetails', 
        'CompanyDetails',
        'IndianEmbassyDetails',
        'BlackLists' 
    ])



data = {
                    "Name": "KOHINOOR SUPPLIERS",
                    "PANDetails": {
                        "PANCount": "1",
                        "PAN": {
                            "PAN": "600534811",
                            "PANIssuedDate": "2069-01-20",
                            "PANIssuedDistrict": "Sunasari"
                        }
                    },
                    "CompanyDetails": {
                        "CompanyCount": "2",
                        "Company": [
                            {
                                "CompanyRegNumber": "1872/069/070",
                                "CompanyRegDate": "NULL",
                                "CompanyRegAuth": "Department of Commerce"
                            },
                            {
                                "CompanyRegNumber": "1872/069/070",
                                "CompanyRegDate": "NULL",
                                "CompanyRegAuth": "Office of Cottage and Small Industry"
                            }
                        ]
                    },
                    "BlackLists": {
                        "BlackListCount": "3",
                        "BlackList": [
                            {
                                "Sector": "Bank and Financial Institutions",
                                "BlacklistNumber": "45442",
                                "BlacklistedDate": "2079-06-05",
                                "BlacklistType": "NON CF",
                                "NatureOfRelation": "Borrower"
                            },
                            {
                                "Sector": "Bank and Financial Institutions",
                                "BlacklistNumber": "32402",
                                "BlacklistedDate": "2078-11-12",
                                "BlacklistType": "NON CF",
                                "NatureOfRelation": "Borrower"
                            },
                            {
                                "Sector": "Bank and Financial Institutions",
                                "BlacklistNumber": "33589",
                                "BlacklistedDate": "2078-12-10",
                                "BlacklistType": "NON CF",
                                "NatureOfRelation": "Borrower"
                            }
                        ]
                    }
                }

#  data_list = []
dicts = {}
data_keys = list(data.keys())
# print(data_keys)
for data_key in data_keys[:1]:
    dicts[data_key] = data[data_key]
    # print(dicts)
for data_key in sorted(data_keys[1:]):
    # print(data_key)
    # print(data[data_key])
    keys = list(data[data_key].keys())
    # print('key------------',keys)
    data_count = int(data[data_key][keys[0]])
    print(data_count)
    if 'PANDetails' in data_key:
        details = data[data_key][keys[1]]
        dicts[data_key] = '|'.join(details.values())
        print('pan========================',dicts)
    if data_count == 1:
        details = data[data_key][keys[1]]
        dicts[data_key] = '|'.join(details.values())
        print('DATACOUNT IS EQUAL TO ONE',dicts)
    elif data_count > 1:
        details = data[data_key][keys[1]]
        # print('detail',details)
        if "BlackList" in data_key:
            dicts[data_key] = ['|'.join(detail.values()) for detail in details]
            # print(dicts)
            continue
            
        else:  
            for detail in details:
                dicts[data_key] = '|'.join(detail.values())
                # print('detttttttttttttttt',dicts[data_key])
                print('COUNT GREATER THAN 1',dicts)
                df.loc[len(df)] = dicts
    elif data_count == 0:
        continue
    # else:
    #     details = data[data_key][keys[1]]
    #     # print('DETAIL',details)
    #     dicts[data_key] = '|'.join(details.values())
    #     df.loc[len(df)] = dicts
    #     # print(dicts)
    # if "BlackList" not in data_key:
    #     df.loc[len(df)] = dicts
    #     print('================',dicts[data_key])
    #     print('================',dicts)
        # del dicts[data_key]
        # print('TTTTTTTTTTt================',dicts)
# df.loc[len(df)] = dicts

3
2
COUNT GREATER THAN 1 {'Name': 'KOHINOOR SUPPLIERS', 'BlackLists': ['Bank and Financial Institutions|45442|2079-06-05|NON CF|Borrower', 'Bank and Financial Institutions|32402|2078-11-12|NON CF|Borrower', 'Bank and Financial Institutions|33589|2078-12-10|NON CF|Borrower'], 'CompanyDetails': '1872/069/070|NULL|Department of Commerce'}
COUNT GREATER THAN 1 {'Name': 'KOHINOOR SUPPLIERS', 'BlackLists': ['Bank and Financial Institutions|45442|2079-06-05|NON CF|Borrower', 'Bank and Financial Institutions|32402|2078-11-12|NON CF|Borrower', 'Bank and Financial Institutions|33589|2078-12-10|NON CF|Borrower'], 'CompanyDetails': '1872/069/070|NULL|Office of Cottage and Small Industry'}
1
pan======================== {'Name': 'KOHINOOR SUPPLIERS', 'BlackLists': ['Bank and Financial Institutions|45442|2079-06-05|NON CF|Borrower', 'Bank and Financial Institutions|32402|2078-11-12|NON CF|Borrower', 'Bank and Financial Institutions|33589|2078-12-10|NON CF|Borrower'], 'CompanyDetails': '1872/069/070|NULL|Office of Cottage and Small Industry', 'PANDetails': '600534811|2069-01-20|Sunasari'}
DATACOUNT IS EQUAL TO ONE {'Name': 'KOHINOOR SUPPLIERS', 'BlackLists': ['Bank and Financial Institutions|45442|2079-06-05|NON CF|Borrower', 'Bank and Financial Institutions|32402|2078-11-12|NON CF|Borrower', 'Bank and Financial Institutions|33589|2078-12-10|NON CF|Borrower'], 'CompanyDetails': '1872/069/070|NULL|Office of Cottage and Small Industry', 'PANDetails': '600534811|2069-01-20|Sunasari'}

In [105]:
df

,Name,DOB,Gender,FatherName,CitizenshipDetails,PassportDetails,DrivingLicenseDetails,VoterIDDetails,PANDetails,CompanyDetails,IndianEmbassyDetails,BlackLists
0,KOHINOOR SUPPLIERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1872/069/070|NULL|Department of Commerce,NaN,[Bank and Financial Institutions|45442|2079-06...
1,KOHINOOR SUPPLIERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1872/069/070|NULL|Office of Cottage and Small ...,NaN,[Bank and Financial Institutions|45442|2079-06...

In [92]:
import pandas as pd

df = pd.DataFrame(columns=[
        'Name',
        'DOB', 
        'Gender', 
        'FatherName', 
        'CitizenshipDetails', 
        'PassportDetails', 
        'DrivingLicenseDetails',
        'VoterIDDetails',
        'PANDetails', 
        'CompanyDetails',
        'IndianEmbassyDetails',
        'BlackLists' 
    ])
    
data = {
                    "Name": "KOHINOOR SUPPLIERS",
                    "PANDetails": {
                        "PANCount": "1",
                        "PAN": {
                            "PAN": "600534811",
                            "PANIssuedDate": "2069-01-20",
                            "PANIssuedDistrict": "Sunasari"
                        }
                    },
                    "CompanyDetails": {
                        "CompanyCount": "2",
                        "Company": [
                            {
                                "CompanyRegNumber": "1872/069/070",
                                "CompanyRegDate": "NULL",
                                "CompanyRegAuth": "Department of Commerce"
                            },
                            {
                                "CompanyRegNumber": "1872/069/070",
                                "CompanyRegDate": "NULL",
                                "CompanyRegAuth": "Office of Cottage and Small Industry"
                            }
                        ]
                    },
                    "BlackLists": {
                        "BlackListCount": "3",
                        "BlackList": [
                            {
                                "Sector": "Bank and Financial Institutions",
                                "BlacklistNumber": "45442",
                                "BlacklistedDate": "2079-06-05",
                                "BlacklistType": "NON CF",
                                "NatureOfRelation": "Borrower"
                            },
                            {
                                "Sector": "Bank and Financial Institutions",
                                "BlacklistNumber": "32402",
                                "BlacklistedDate": "2078-11-12",
                                "BlacklistType": "NON CF",
                                "NatureOfRelation": "Borrower"
                            },
                            {
                                "Sector": "Bank and Financial Institutions",
                                "BlacklistNumber": "33589",
                                "BlacklistedDate": "2078-12-10",
                                "BlacklistType": "NON CF",
                                "NatureOfRelation": "Borrower"
                            }
                        ]
                    }
                }
for key, value in data.items():
    if key == "CompanyDetails":
        for company in value['Company']:
            row_data = {
                "Name": data["Name"],
                "PANDetails": '|'.join(data["PANDetails"]["PAN"].values()),
                "CompanyDetails": '|'.join(company.values()),
                "BlackLists": '|'.join(blacklist.values())  # Assuming blacklist is defined somewhere
            }
            df = df.append(row_data, ignore_index=True)
    else:
        # Handle other keys in a similar way if needed
        pass

# print(df)

NameError: name 'blacklist' is not defined

In [1]:
import pandas as pd
from openpyxl import Workbook 
from openpyxl.worksheet.datavalidation import DataValidation

# Sample data for the DataFrame
data = {
    'Name': ['John', 'Alice', 'Bob'],
    'Father_Name': ['Doe', 'Smith', 'Johnson'],
    'Gender': ['Male', 'Female', 'Male']
}

# Create a DataFrame from the data
df = pd.DataFrame(data)

# Create a new Excel writer object
excel_writer = pd.ExcelWriter('output.xlsx', engine='openpyxl')

# Write the DataFrame to Excel
df.to_excel(excel_writer, index=False, sheet_name='Sheet1')

# Get the workbook and worksheet objects
workbook = excel_writer.book
worksheet = excel_writer.sheets['Sheet1']

# Define the list of options for the dropdown
gender_options = ['Male', 'Female']

# Define the range where the dropdown will be applied (assuming Gender column starts from column C)
dropdown_range = 'C2:C{}'.format(len(df) + 1)

# Create a DataValidation object for the dropdown
data_validation = DataValidation(type="list", formula1='"{}"'.format(','.join(gender_options)), allow_blank=True)

# Add the data validation to the specific column
worksheet.add_data_validation(data_validation)
data_validation.add(dropdown_range)

# Save the Excel file
excel_writer.save()

print("Dropdown list added to the 'Gender' column in the Excel file.")

Dropdown list added to the 'Gender' column in the Excel file.